### ISSUE TITLE
Using Log to receive chat messages

### ISSUE THREAD

**Issue by Jpine89** [Challengermode/CoreRcon#12]
So, I've been struggling with this issue for the last few days. 

I'm trying to set up my squad server so we can record chats in a txt file but I can't get anything to event print to console. 

I followed an example from the tf2 and set it up, and change the log.listen to ListenRaw just to get anything but nothing printing out. 

Not sure if I'm missing something, I have the port open and I can connect via rcon to send commands but receiving packets doesnt seem to be working and I'm not getting any errors.

**Comment by xobust** [comment]
Hey,
You can try sending packages to that port from your own computer and see if the listener listening at all, with netcat for example. 
And then try from an external host to check that the port is forwarded correctly. 
Did you use logaddress_add? What does logaddress_list say?

**Comment by Jpine89** [comment]
So tried logaddress_list, and looks like that isn't a command that Squad uses. 

I can at least add some update to this since I've learned more about how the application/rcon worked over the last few days. 

Using Wireshark I can see that rcon was sending packets to me, but it was sending it to a different port then what I was using. 

That's pretty much where I'm at right now is trying to figure out how to setup the port to receive messages. There is someone I'm talking to that has figured this out and I'm waiting on their response so once I do get it, I'll probably pass it on in this Issue for anyone else planning to use CoreRcon for Squad.

**Comment by Jpine89** [comment]
So tried logaddress_list, and looks like that isn't a command that Squad uses. 

I can at least add some update to this since I've learned more about how the application/rcon worked over the last few days. 

Using Wireshark I can see that rcon was sending packets to me, but it was sending it to a different port then what I was using. 

That's pretty much where I'm at right now is trying to figure out how to setup the port to receive messages. There is someone I'm talking to that has figured this out and I'm waiting on their response so once I do get it, I'll probably pass it on in this Issue for anyone else planning to use CoreRcon for Squad.

**Comment by Jpine89** [comment]
So Squad just requires you to essentially spam the sendCommand command with listplayers or listSquads. That will queue up chat.
