### ISSUE TITLE
Log.Listen for more than Chat

### ISSUE THREAD

**Issue by RuneNyhuus** [Challengermode/CoreRcon#13]
log.Listen<KillFeed>(kill =>
                {
                    Console.WriteLine($"Player {kill.Killer.Name} ({kill.Killer.Team}) killed {kill.Killed.Name} ({kill.Killed.Team}) with {kill.Weapon}");
                });

I can't seem to get this to work?
Do CSGO only supports Chat?

**Comment by xobust** [comment]
Hey, Sorry for the late reply. 
The standard KillFeed parsers dosn't work with CSGO.
I made a specialized version that parses all the csgo data. 
This should work:
```
  log.Listen<Frag>(kill =>
             {
                 Console.WriteLine($"Player {kill.Killer.Name} ({kill.Killer.Team}) killed {kill.Killed.Name} ({kill.Killed.Team}) with {kill.Weapon}");
             });
```

**Comment by RuneNyhuus** [comment]
I will give it a try. Thank you 👍

**Comment by xobust** [comment]
Closed due to inactivity.
