### ISSUE TITLE
"IPAddress" not found

### ISSUE THREAD

**Issue by zLauch** [Challengermode/CoreRcon#19]
if i add this code
```
var rcon = new RCON(IPAddress.Parse("10.0.0.1"), 27015, "secret-password");
await rcon.ConnectAsync();
```
 it tells me that the "IPAddress" in not in the Context.
 
 is it possible to send me a project which is working and using  this libary

**Comment by xobust** [comment]
Hey I Forgot to add the `System.Net` dependency updating the ReadMe.
Add this to the top of your file: `using System.Net;`
