### ISSUE TITLE
ServerQuery.Info hangs, never completes task

### ISSUE THREAD

**Issue by vividuwu** [Challengermode/CoreRcon#20]
I'm writing a Discord bot to handle Minecraft servers for user communities, and I have a method called "Status" that represents a command to query a Minecraft server.  To do this, I pull an object  containing the address of the server from a database, get it's hostname through DNS, then sure the ServerQuery.Info() method, but it hangs every time.

Here's the code:
````csharp
public async Task Status(CommandContext context) {
            MinecraftServer server = DBManager.GetMinecraftServerDocument(context.Guild.Id);

            DiscordEmbedBuilder embedBuilder = new DiscordEmbedBuilder();
            if (server == null) {
                embedBuilder.WithColor(DiscordColor.Red);
                embedBuilder.WithTitle("This Discord server does not have an associated Minecraft server");
                embedBuilder.WithFooter("Use the \"minecraft register <server address>\" command to register one!");
                await context.Channel.SendMessageAsync(embedBuilder.Build());

                return;
            }

            IPAddress serverAddress = Dns.GetHostAddresses(server.Address)[0];

            Console.WriteLine($"Performing server query on {serverAddress}");

            MinecraftQueryInfo status = ServerQuery.Info(serverAddress, 25575,   ServerQuery.ServerType.Minecraft).GetAwaiter().GetResult() as MinecraftQueryInfo;


            if (status.Players == null) {
                await context.Channel.SendMessageAsync("Something went wrong with the status request...");
                return;
            } else Console.WriteLine("Completed query");

            embedBuilder.Color = DiscordColor.Green;
            embedBuilder.Title = $"{status.HostIp} Status";
            // embedBuilder.Description = $"{status.}";
            embedBuilder.AddField("Version:", status.Version);
            embedBuilder.AddField("Game Type:", status.Gametype);
            embedBuilder.AddField("Players Online:", $"{status.NumPlayers} / {status.MaxPlayers}");
            DiscordEmbed embed = embedBuilder.Build();

            await context.Channel.SendMessageAsync(embed);
        }
// I don't think I'm using this incorrectly, but it's possible that I am. It gives the same result even when awaiting the Task the traditional way.  I really appreciate anyone who gives feedback on this, thanks for the help!

**Comment by xobust** [comment]
Hello, sorry for my inactivity in this repo. 
Including the code is very helpful I will see if I can reproduce it. 
How come you don't use **await** for `ServerQuery.Info`?

**Comment by nickmartin1ee7** [comment]
I also have this issue where the Query seems to hang.
```cs
public async Task<MinecraftQueryInfo> GetStatusAsync(ushort port) =>
            await ServerQuery.Info(_host, port, ServerQuery.ServerType.Minecraft) as MinecraftQueryInfo;
```
This request seems to never resolve in the minutes I left it running.

Minecraft server version:
`This server is running Paper version git-Paper-268 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e2f743d)`

**Comment by vividuwu** [comment]
@xobust I originally had been awaiting the call, but also tried using the `GetAwaiter().GetResult()` to forcibly end the wait for the method completion, which didn't end up solving this issue.

**Comment by xobust** [comment]
@vividuwu  I could reproduce this error when the query was not running on the port. 
I added a timeout parameter that will time out if the server does not respond. 
To get an answer from the server make sure that that `enable-query` and `query.port` is set correctly in server.properties. 
Checkout the latest release on [nugget.org](https://www.nuget.org/packages/CoreRCON/5.0.3)

**Comment by vividuwu** [comment]
@xobust Thank you so much for looking into the issue, I'll definitely have to continue using the package
