### ISSUE TITLE
Provide package to include as third party library

### ISSUE THREAD

**Issue by nilshelmig** [Challengermode/CoreRcon#4]
Hello,
since the main library is unmaintained I would like to use this version, which has some great improvements 😃 

Could this repository provide a package to include this library in other projects. Best solution would be a package on NuGet.

Cheers 👋

**Comment by xobust** [comment]
Thanks for finding our package :wave: 
We would like to mark it as a fork, but I'm not sure if that is possible without recreating the repo. 
We would gladly provide a NuGet package for our implementation.
I wanted to reach out to ScottKaye about maintaining this but I could not find an email, I will open an issue in the main repo to ask what he thinks about this fork.

In the meantime, I can create a new NuGet package, maybe "Challengermode.CoreRCON" would be an appropriate name.

**Comment by xobust** [comment]
You can now download the latest version of this package from [NuGet](https://www.nuget.org/packages/CoreRCON)
