### ISSUE TITLE
doubt about rconserver

### ISSUE THREAD

**Issue by marcelobertinatto** [Challengermode/CoreRcon#43]
hi guys,

first of all, thank you so much for this library. 

second, I'd like to understand and check if it's possible to get everything that is happening in the CSGO server, i.e. kills, players, rounds, chat among players and etc.

I am trying to use your example, but nothing happened as you can see in the print sreen below:

![Capturar](https://github.com/Challengermode/CoreRcon/assets/53238758/d8beb01e-9f9f-4af1-9ba2-3e5f59ce5152)
![Capturar2](https://github.com/Challengermode/CoreRcon/assets/53238758/ce6a3ca5-073f-45e3-b678-16e940d02ab6)

I could see something related to logaddress_add to just connect and get the results, but i could not make this working.

Would you mind to explain to me or if you have some example that i can do it ?

thank you,
Marcelo.

**Comment by xobust** [comment]
Hey late response. 
There could be many reasons why you are not getting logs. 
Did you check your firewall to start with? 
You can reopen this issue if you still need help
