### ISSUE TITLE
Parser not works on CS2

### ISSUE THREAD

**Issue by fpaezf** [Challengermode/CoreRcon#44]
Hi, i'm trying to retrieve the chat on a cs2 gameserver. This is my code in VB.NET but does nothing... Can you help me?.

  Dim log = New LogReceiver(GAMESERVERPORT, New IPEndPoint(IPAddress.Parse("GAMESERVERIP"), GAMESERVERPORT))

        log.Listen(Of ChatMessage)(Sub(chat)
                                       RichTextBox1.AppendText($"Chat message: {chat.Player.Name} said {chat.Message} on channel {chat.Channel}")
                                       MsgBox($"Chat message: {chat.Player.Name} said {chat.Message} on channel {chat.Channel}")
                                   End Sub)

**Comment by xobust** [comment]
Hey!
I haven't tested the CS:GO chat parser for CS2 yet. 
It could be good to start with a raw log listener. 
To get started make sure that you have forwarded the listning port & registered the correct address using `logaddress_add_http`

**Comment by fpaezf** [comment]
Don't worry, i wrote my own parser in vb.net. thanks anyway!!
