### ISSUE TITLE
L4D2 Failed to parse server response

### ISSUE THREAD

**Issue by Shepard199** [Challengermode/CoreRcon#5]
Hello, I encountered such a problem when using the status command

**Comment by xobust** [comment]
Hi, what did you try to parse it as? 
I'm guessing you tried to parse it as a Status. Perhaps l4d2s status message is different from csgo and tf2.
could you send me an example of a message that fails to parse? 
I could try to fix it if you send me some more info.

**Comment by ceifa** [comment]
@xobust Same problem when trying to parse on Garry's Mod.
If i send a status command and try to get the return as plain string, the string returned is empty.

If i send a status directly on server console, status returns beautifully.

**Comment by xobust** [comment]
Okay, I will try to improve the parser. 
But some example outputs would be great.

**Comment by ceifa** [comment]
I think it's not a parser problem, as i said, when i try to send the command and get the return as plain string, it returns an empty string. My code:

```
var rconClient = new RCON(ip, port, rconPassword, 0, 1000, false);
await rconClient.ConnectAsync();
var status = await rconClient.SendCommandAsync("status");
Console.WriteLine(string.IsNullOrEmpty(status));
var ip = await rconClient.SendCommandAsync("ip");
Console.WriteLine(string.IsNullOrEmpty(ip));
Console.WriteLine(ip);
```

Console output:

```
1/23/2020 1:32:42 PM - Error reading RCON packet from server: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
True
False
"ip" = "localhost"
 - Overrides IP for multihomed hosts
```

When i try to send the status command from the server console(native steam rcon connection with srcds + steamcmd), i get this output:

```
hostname: [BR] Lory | Deathrun
version : 2019.11.12/24 7671 secure
udp/ip  : (private ip here, i will not show for security reasons)  (public ip: 35.247.194.242)
map     : deathrun_portal at: 0 x, 0 y, 0 z
players : 5 (24 max)
# userid name                uniqueid            connected ping loss state  adr
(players here, i will not show for security reasons)
```

**Comment by ceifa** [comment]
@xobust Do you have any suggestions on this? Maybe i can make a PR to fix it.

**Comment by xobust** [comment]
Hi @ceifa. 
I have been busy with a lot of stuff. 
The problem is in https://github.com/Challengermode/CoreRcon/blob/master/src/CoreRCON/Parsers/Standard/Status.cs 
The regex contains a lot of required fields that might not exist in some games. 
You could either modify the parser to make the fields optional or make a specialized parser for left4deads status messages. 

I tested the regex using regexer: https://regexr.com/4umgb

**Comment by xobust** [comment]
Hi, I did some improvements to the status parser, let me know if you still have problems.
