### ISSUE TITLE
Auth failure when attempting to connect to a Palworld server.

### ISSUE THREAD

**Issue by Trekkan** [Challengermode/CoreRcon#56]
I'm not sure what's wrong, but the RCON connection does work with a command line RCON utility (https://github.com/gorcon/rcon-cli).
I know the game isn't listed as supported, but was hoping it would be something quick to fix?  Thanks much regardless, this is a great library.

**Comment by ExusAltimus** [comment]
Check https://github.com/Challengermode/CoreRcon/pull/57

**Comment by huliganhak** [comment]
Palworld server

string respnose = await rcon.SendCommandAsync("info");

System.TimeoutException: 'Timeout while waiting for response from server'
How can I fix this problem?

**Comment by xobust** [comment]
Still working on Pallworld support see #57

**Comment by xobust** [comment]
New version with Palworld suport should be up soon
https://www.nuget.org/packages/CoreRCON/5.4.0
