### ISSUE TITLE
No documentation ServerQueryPlayer

### ISSUE THREAD

**Issue by RuneNyhuus** [Challengermode/CoreRcon#70]
How to use the ServerQueryPlayer function ?
I'm trying to get players info on my CS2 server.

Is this possible?

**Comment by xobust** [comment]
It was possible in CS:GO if `host_players_show 2` is set on the server. 
I am not sure if the function is implemented for CS2 though. 
You can try it by calling:
`ServerQuery.Players(IPEndPoint.Parse("ip:port"));`
