### ISSUE TITLE
CSGO Failed to parse status

### ISSUE THREAD

**Issue by JamesDolphin** [Challengermode/CoreRcon#8]
Status status = await Rcon.SendCommandAsync<Status>("status");

Is throwing an exception "Failed to parse server response"

Server response

`hostname: test server | hostname
version : 1.37.4.4/13744 1081/7776 secure  [G:1:3059110] 
udp/ip  : 111.11.111.111:22222  (public ip: 111.11.111.111)
os      :  Linux
type    :  community dedicated
map     : de_inferno
gotv[0]:  port 11223, delay 105.0s, rate 24.0
players : 1 humans, 1 bots (12/0 max) (not hibernating)`

Looking at the Status Parser its not taking into consideration the (not hibernating) but that surely isn't causing an exception to be thrown

**Comment by JamesDolphin** [comment]
I have tried using my own parser to accommodate the changes in the status text (os etc) but its still throwing an exception

**Comment by xobust** [comment]
It seems like there have been some changes to the format of the "status" output. 
I have made a more robust parser for status messages now. 
Let me know if you still have Issues.
