### ISSUE TITLE
Error reading RCON packet from server: Index was out of range.

### ISSUE THREAD

**Issue by MostRush** [Challengermode/CoreRcon#9]
When i send command trough RCON to my minecraft server it's successfully executed, but answer from server generate error: "Error reading RCON packet from server: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')"

Sent command is an plugin's command. And error generated only with any plugin's commands.
With a command of the kernel of minecraft such an error isn't generated.

I know such program as "mcrcon". In this program all plugin's commands successfully return answer.

Perhaps I doing something wrong. Or CoreRcon can't get answer from such commands.

**Comment by xobust** [comment]
Hey, sorry for the delay. 
It should be fixed in the [latest version](https://www.nuget.org/packages/CoreRCON/4.7.0). 
If not please reopen the issue and let me know if the output has changed.
